{{- if and (.Values.adminUser.enabled) (not .Values.adminUser.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-influxdb2-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "influxdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: auth
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  admin-password: {{ required "adminUser.password is required when existingSecret is not set" .Values.adminUser.password | quote }}
  admin-token: {{ required "adminUser.token is required when existingSecret is not set" .Values.adminUser.token | quote }}
{{- end }}
