apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app.kubernetes.io/instance: wordpress
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /mnt/data/mysql
